name = "shortener"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-09-17"

kv_namespaces = [
    { binding = "PUBLIC", preview_id = "a2c9c9fbec25420e88ed089475cf2a2c", id = "38f6d9e5689b4b2bb676180c244eb8d0" }
]