name = "shrt"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-09-17"

kv_namespaces = [
    { binding = "URL_HASH", id = "76764f1bc8f34899b95d06824985924d", preview_id = "d5e1b5ee6d0745ae989514c950969bf1" },
    { binding = "HASH_URL", id = "ec9e7a353a6647dc9ade22099d8ffa43", preview_id = "a9acadc08b284cbc946090a7bdc1a6b7" }
]